parameters:
#    ceb_goldbook.example.class: Ceb\GoldbookBundle\Example

services:
#    ceb_goldbook.example:
#        class: %ceb_goldbook.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
