ceb_contact_contact:
    pattern:  /Contact
    defaults: { _controller: CebAutreBundle:Default:contact }

ceb_partenaire_homepage:
    pattern:   /partenaires
    defaults: { _controller: CebAutreBundle:Default:partenaire }

ceb_present_homepage:
    pattern:   /present
    defaults: { _controller: CebAutreBundle:Default:presentation }